# Generated by Django 6.0.6 on 2026-06-16 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MDC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'MDC',
                'verbose_name_plural': 'MDCs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultant', models.CharField(help_text='The consultant who leads this team.', max_length=100)),
                ('specialty', models.CharField(help_text="e.g. 'Thyroid and breast', 'Colorectal cancer'.", max_length=100)),
            ],
            options={
                'ordering': ['consultant'],
            },
        ),
    ]
