# Generated by Django 6.0.6 on 2026-09-05 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_mdc_meeting_weekday'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FellowAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rotations_assigned', to=settings.AUTH_USER_MODEL)),
                ('fellow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to=settings.AUTH_USER_MODEL)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotations', to='teams.team')),
            ],
            options={
                'ordering': ['-start_date', 'fellow__username'],
                'constraints': [models.UniqueConstraint(fields=('fellow', 'team', 'start_date'), name='unique_fellow_team_rotation')],
            },
        ),
    ]
