# Generated by Django 6.0.6 on 2026-06-19 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0004_patient_next_review_date_patient_watch_wait_start_and_more'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MDCListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_date', models.DateField(help_text='The MDC meeting this patient is listed for.')),
                ('presented', models.BooleanField(default=False, help_text='Has this patient been discussed yet?')),
                ('decision', models.TextField(blank=True, help_text='MDC decision / notes (filled after discussion).')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('mdc', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='listings', to='teams.mdc')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mdc_listings', to='patients.patient')),
            ],
            options={
                'ordering': ['meeting_date', 'patient__name'],
            },
        ),
    ]
