# Generated by Django 6.0.6 on 2026-09-05 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdc', '0002_unique_patient_per_mdc_meeting'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdclisting',
            name='decided_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='mdclisting',
            name='decision_category',
            field=models.CharField(blank=True, choices=[('SURGERY', 'Surgery'), ('NACT', 'Neoadjuvant chemotherapy'), ('TNT', 'Total neoadjuvant therapy (rectal)'), ('REFER_MEDICAL', 'Refer to medical oncology'), ('MORE_WORKUP', 'Further workup needed'), ('SURVEILLANCE', 'Surveillance'), ('WATCH_WAIT', 'Watch & wait'), ('PALLIATIVE', 'Best supportive / palliative care')], help_text='The structured outcome — this is what moves the patient on.', max_length=16),
        ),
        migrations.AddField(
            model_name='mdclisting',
            name='is_postop',
            field=models.BooleanField(default=False, help_text='This listing is the post-operative re-discussion, not the initial one.'),
        ),
    ]
