# Generated by Django 6.0.6 on 2026-09-05 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdc', '0004_guidelinesuggestion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MDCAgentReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation', models.TextField(help_text='The draft currently held for sign-off.')),
                ('status', models.CharField(choices=[('AWAITING', 'Awaiting physician sign-off'), ('APPROVED', 'Approved by physician')], default='AWAITING', max_length=10)),
                ('revisions', models.PositiveSmallIntegerField(default=0, help_text='How many times a physician sent it back.')),
                ('last_feedback', models.TextField(blank=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_reviews_approved', to=settings.AUTH_USER_MODEL)),
                ('listing', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_review', to='mdc.mdclisting')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_reviews_started', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
