# Generated by Django 6.0.6 on 2026-09-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdc', '0005_mdcagentreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidelinesuggestion',
            name='coverage_note',
            field=models.CharField(blank=True, help_text="Warning shown when no guideline for this patient's disease is indexed.", max_length=300),
        ),
        migrations.AddField(
            model_name='guidelinesuggestion',
            name='refused',
            field=models.BooleanField(default=False, help_text='The brain declined because no indexed guideline covers this disease.'),
        ),
    ]
