# Generated by Django 6.0.6 on 2026-09-05 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mdc', '0006_guidelinesuggestion_coverage_note_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidelinesuggestion',
            name='grade_attempts',
            field=models.PositiveSmallIntegerField(default=0, help_text='How many times the answer was rewritten after grading.'),
        ),
        migrations.AddField(
            model_name='guidelinesuggestion',
            name='graded_pass',
            field=models.BooleanField(blank=True, help_text='Did the grader find every claim supported? Null means it did not run.', null=True),
        ),
        migrations.AddField(
            model_name='guidelinesuggestion',
            name='grader_feedback',
            field=models.TextField(blank=True, help_text='What the grader still objected to, if it never passed.'),
        ),
    ]
