# Generated by Django 6.0.6 on 2026-06-19 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('mrn', models.CharField(help_text='Medical Record Number — must be unique.', max_length=20, unique=True, verbose_name='MRN')),
                ('date_of_birth', models.DateField()),
                ('diagnosis', models.CharField(max_length=200)),
                ('specialty', models.CharField(choices=[('GENERAL', 'General surgical oncology'), ('THYROID_BREAST', 'Thyroid & breast'), ('HPB', 'HPB'), ('UPPER_GI', 'Upper GI'), ('COLORECTAL', 'Colorectal'), ('SARCOMA', 'Sarcoma')], max_length=20)),
                ('stage', models.CharField(choices=[('REGISTERED', 'Registered (prep clinic)'), ('CLINIC', 'Consultant clinic'), ('WORKUP', 'Workup in progress'), ('MDC', 'Awaiting / at MDC'), ('SURGERY', 'Planned for surgery'), ('NACT', 'On NACT'), ('TNT', 'On TNT (rectal)'), ('REFERRED', 'Referred to medical team'), ('POSTOP', 'Post-op follow-up'), ('SURVEILLANCE', 'Surveillance')], default='REGISTERED', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(help_text='The team this patient is assigned to.', on_delete=django.db.models.deletion.PROTECT, related_name='patients', to='teams.team')),
            ],
            options={
                'ordering': ['-registered_at'],
            },
        ),
    ]
