# Generated by Django 6.0.6 on 2026-06-19 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='specialty',
            field=models.CharField(choices=[('GENERAL', 'General surgical oncology'), ('BREAST', 'Breast'), ('THYROID', 'Thyroid'), ('HPB', 'HPB'), ('UPPER_GI', 'Upper GI'), ('COLORECTAL', 'Colorectal'), ('SARCOMA', 'Sarcoma')], max_length=20),
        ),
    ]
