# Generated by Django 6.0.6 on 2026-06-19 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_alter_patient_specialty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='stage',
            field=models.CharField(choices=[('REGISTERED', 'Registered (prep clinic)'), ('CLINIC', 'Consultant clinic'), ('WORKUP', 'Workup in progress'), ('MDC', 'Awaiting / at MDC'), ('SURGERY', 'Planned for surgery'), ('NACT', 'On NACT'), ('TNT', 'On TNT (rectal)'), ('RESTAGING', 'Restaging (awaiting results)'), ('REFERRED', 'Referred to medical team'), ('POSTOP', 'Post-op follow-up'), ('SURVEILLANCE', 'Surveillance')], default='REGISTERED', max_length=20),
        ),
    ]
