# Generated by Django 6.0.6 on 2026-06-19 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patient_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='next_review_date',
            field=models.DateField(blank=True, help_text='Expected date of next investigations / results check (restaging or W&W).', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='watch_wait_start',
            field=models.DateField(blank=True, help_text='Date watch-and-wait began (W&W patients only).', null=True, verbose_name='Watch & wait start'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='stage',
            field=models.CharField(choices=[('REGISTERED', 'Registered (prep clinic)'), ('CLINIC', 'Consultant clinic'), ('WORKUP', 'Workup in progress'), ('MDC', 'Awaiting / at MDC'), ('SURGERY', 'Planned for surgery'), ('NACT', 'On NACT'), ('TNT', 'On TNT (rectal)'), ('RESTAGING', 'Restaging (awaiting results)'), ('REFERRED', 'Referred to medical team'), ('POSTOP', 'Post-op follow-up'), ('SURVEILLANCE', 'Surveillance'), ('WATCH_WAIT', 'Watch & wait')], default='REGISTERED', max_length=20),
        ),
    ]
