# Generated by Django 6.0.6 on 2026-09-05 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_patient_next_review_date_patient_watch_wait_start_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='clinical_stage',
            field=models.CharField(blank=True, help_text="Clinical stage, e.g. 'cT4N+', 'T3N2'.", max_length=60),
        ),
        migrations.AddField(
            model_name='patient',
            name='comorbidities',
            field=models.TextField(blank=True, help_text="Background line for the slide, e.g. 'HTN, DM, non-smoker, PS 0-1'."),
        ),
        migrations.AddField(
            model_name='patient',
            name='family_history',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='genetic_testing',
            field=models.CharField(blank=True, help_text="e.g. 'Pending', 'Negative', 'BRCA1 positive'. Shown at the top of every slide.", max_length=120),
        ),
        migrations.AddField(
            model_name='patient',
            name='sex',
            field=models.CharField(blank=True, choices=[('F', 'Female'), ('M', 'Male')], max_length=6),
        ),
        migrations.CreateModel(
            name='SurgeryBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('planned_date', models.DateField()),
                ('procedure', models.CharField(help_text="e.g. 'Open APR', 'Right hemicolectomy'.", max_length=200)),
                ('performed', models.BooleanField(default=False)),
                ('performed_on', models.DateField(blank=True, null=True)),
                ('final_pathology', models.TextField(blank=True, help_text='Final histopathology — carried onto the post-op MDC slide.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='surgeries_listed', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surgery_bookings', to='patients.patient')),
            ],
            options={
                'ordering': ['planned_date'],
            },
        ),
        migrations.CreateModel(
            name='TreatmentCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NACT', 'Neoadjuvant chemotherapy'), ('TNT', 'Total neoadjuvant therapy (rectal)')], max_length=6)),
                ('regimen', models.CharField(help_text="e.g. 'XELOX x 6', 'AC-T'.", max_length=120)),
                ('total_cycles', models.PositiveSmallIntegerField()),
                ('completed_cycles', models.PositiveSmallIntegerField(default=0)),
                ('start_date', models.DateField()),
                ('next_cycle_date', models.DateField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('restaging_alert_sent_on', models.DateField(blank=True, null=True)),
                ('results_alert_sent_on', models.DateField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_courses', to='patients.patient')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Investigation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('COLONOSCOPY', 'Colonoscopy'), ('SIGMOIDOSCOPY', 'Sigmoidoscopy'), ('GASTROSCOPY', 'Gastroscopy / OGD'), ('PATHOLOGY', 'Pathology'), ('FNA', 'FNA / core biopsy'), ('MAMMOGRAM', 'Mammogram'), ('BREAST_US', 'Breast ultrasound'), ('NECK_US', 'Neck ultrasound'), ('CAP_CT', 'CAP CT'), ('PELVIC_MRI', 'Pelvic MRI'), ('ABDOMEN_MRI', 'Abdomen MRI'), ('BREAST_MRI', 'Breast MRI'), ('LOCAL_MRI', 'MRI of primary site'), ('PET_CT', 'PET scan'), ('BONE_SCAN', 'Bone scan'), ('CEA', 'CEA'), ('TUMOR_MARKERS', 'Tumour markers'), ('THYROID_FUNCTION', 'Thyroid function'), ('GENETICS', 'Genetic testing'), ('ECHO', 'Echocardiogram'), ('PFT', 'Pulmonary function tests')], max_length=24)),
                ('purpose', models.CharField(choices=[('BASELINE', 'Baseline workup'), ('RESTAGING', 'Restaging')], default='BASELINE', max_length=12)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ORDERED', 'Ordered'), ('READY', 'Result ready')], default='PLANNED', max_length=10)),
                ('required', models.BooleanField(default=True, help_text='Required items gate MDC presentation.')),
                ('ordered_on', models.DateField(blank=True, null=True)),
                ('resulted_on', models.DateField(blank=True, null=True)),
                ('result_text', models.TextField(blank=True, help_text='The report text, as it will appear on the MDC slide.')),
                ('suggested_by_ai', models.BooleanField(default=False)),
                ('rationale', models.TextField(blank=True, help_text='Why this was requested (guideline citation, if AI-suggested).')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations', to='patients.patient')),
            ],
            options={
                'ordering': ['purpose', 'kind'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'kind', 'purpose'), name='unique_investigation_per_patient_purpose')],
            },
        ),
    ]
