# Generated by Django 6.0.6 on 2026-09-05 05:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_patient_clinical_stage_patient_comorbidities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='pharmacy_mrn',
            field=models.CharField(blank=True, help_text="This patient's MRN in the pharmacy system, for the peri-op medication check. Blank means no medication record is linked.", max_length=20),
        ),
        migrations.CreateModel(
            name='ReportExtraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Awaiting clinician review'), ('CONFIRMED', 'Confirmed by clinician'), ('REJECTED', 'Rejected by clinician')], default='PENDING', max_length=10)),
                ('raw_fields', models.JSONField(help_text='What the extractor returned, kept unchanged for audit.')),
                ('confirmed_fields', models.JSONField(blank=True, help_text='What the clinician confirmed, after any corrections.', null=True)),
                ('needs_human_review', models.BooleanField(default=False, help_text="The extractor's own flag that this note is ambiguous.")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('investigation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extraction', to='patients.investigation')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extractions_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
