# Generated by Django 6.0.6 on 2026-09-05 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_patient_pharmacy_mrn_reportextraction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='pharmacy_mrn',
        ),
        migrations.AddField(
            model_name='patient',
            name='ehr_synced_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drug_name', models.CharField(max_length=120)),
                ('drug_class', models.CharField(blank=True, max_length=120)),
                ('high_alert', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('started_on', models.DateField(blank=True, null=True)),
                ('synced_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='patients.patient')),
            ],
            options={
                'ordering': ['drug_name'],
                'constraints': [models.UniqueConstraint(fields=('patient', 'drug_name'), name='unique_drug_per_patient')],
            },
        ),
    ]
