# Generated by Django 6.0.6 on 2026-09-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_remove_patient_pharmacy_mrn_patient_ehr_synced_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investigation',
            name='kind',
            field=models.CharField(choices=[('PATH_REVIEW', 'Pathology review (tumour board)'), ('CBC', 'CBC'), ('CMP', 'CMP (LFTs + renal)'), ('PERFORMANCE_STATUS', 'Performance status'), ('PRIOR_IMAGING', 'Review of prior / outside imaging'), ('FERTILITY', 'Fertility counselling'), ('COLONOSCOPY', 'Colonoscopy'), ('SIGMOIDOSCOPY', 'Sigmoidoscopy'), ('GASTROSCOPY', 'Gastroscopy / OGD'), ('PATHOLOGY', 'Pathology'), ('FNA', 'FNA / core biopsy'), ('EUS', 'Endoscopic ultrasound (EUS)'), ('STAGING_LAP', 'Staging laparoscopy'), ('DRE', 'DRE for tumour distance'), ('LARYNGOSCOPY', 'Laryngoscopy (vocal cords)'), ('MAMMOGRAM', 'Mammogram'), ('BREAST_US', 'Breast ultrasound'), ('NECK_US', 'Neck ultrasound'), ('CAP_CT', 'CAP CT'), ('PELVIC_MRI', 'Pelvic MRI'), ('ABDOMEN_MRI', 'Abdomen MRI'), ('BREAST_MRI', 'Breast MRI'), ('LOCAL_MRI', 'MRI of primary site'), ('PET_CT', 'PET scan'), ('BONE_SCAN', 'Bone scan'), ('ABDOMEN_US', 'Abdomen ultrasound'), ('CXR', 'Chest X-ray'), ('PANCREAS_CT', 'Pancreas-protocol CT'), ('MRCP', 'MRCP'), ('TRIPHASIC', 'Triphasic CT or MRI'), ('CEA', 'CEA'), ('TUMOR_MARKERS', 'Tumour markers'), ('THYROID_FUNCTION', 'Thyroid function'), ('GENETICS', 'Genetic testing'), ('BIOMARKERS', 'ER / PR / HER2 + Ki-67'), ('HER2', 'HER2'), ('PD_L1', 'PD-L1'), ('MMR_MSI', 'MMR / MSI'), ('RAS_BRAF', 'RAS / BRAF'), ('CA_19_9', 'CA 19-9'), ('CALCITONIN', 'Calcitonin'), ('RET_GENETIC', 'RET genetic testing'), ('AFP', 'AFP'), ('HEPATITIS', 'Hepatitis serology'), ('CHILD_PUGH', 'Child-Pugh score'), ('ECHO', 'Echocardiogram'), ('PFT', 'Pulmonary function tests')], max_length=32),
        ),
    ]
