# Generated by Django 6.0.6 on 2026-09-05 05:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0005_patient_clinical_stage_patient_comorbidities_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('NEW_PATIENT', 'New patient registered to your team'), ('MDC_LISTED', 'Patient listed for MDC'), ('WORKUP_READY', 'Workup complete — ready for MDC'), ('DECISION', 'MDC decision recorded'), ('RESTAGING_DUE', 'Last cycle approaching — order restaging'), ('RESTAGING_READY', 'Restaging reports ready for review'), ('POSTOP_MDC_DUE', 'Post-op patient needs re-discussion'), ('SURGERY_LISTED', 'Patient added to the surgery schedule')], max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('emailed_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='patients.patient')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
